version: '3'
services:

  mysql:
    container_name: mysql
    image: mariadb:10.8.2-rc-focal
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:php7.4-apache
    volumes:
      - ./data/site.ru:/var/www/site.ru
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    ports:
      - 8082:80
    restart: always

  nginx:
    container_name: nginx
    image: nginx:1.21.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled          
      - ./data/site.ru:/var/www/site.ru
      - ./var/log/nginx:/var/log/nginx
    ports:
      - 80:80
    links:
      - wordpress

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin:5.0
    restart: always
    links:
      - mysql:mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

