version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.21.6
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/nginx/sites-available:/etc/nginx/sites-available
      - ./apps/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./data/site-2.ru:/var/www/site-2.ru
      - ./var/log/nginx:/var/www/site.ru/log/nginx
      - ./var/log/nginx:/var/www/site-2.ru/log/nginx
    ports:
      - 127.0.0.1:80:80
    links:
      - wordpress
    depends_on:
      - apache
      - wordpress
    restart: always
      
  php:
    container_name: php
    image: php:7.2-fpm
    volumes:
      - ./data/site-2.ru:/var/www/site-2.ru
    restart: always
      
  apache:
    container_name: apache
    image: httpd:2.4
    volumes:
      - ./data/site-2.ru:/var/www/site-2.ru
      - ./apps/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./var/log/apache:/var/www/site-2.ru/log/apache2
    depends_on:
      - php
    restart: always

  mysql:
    container_name: mysql
    image: mariadb:10.8.2-rc-focal
    env_file: .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress:php7.4-apache
    env_file: .env
    volumes:
      - ./data/site.ru:/var/www/html
      - ./var/log/apache:/var/log/apache2
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    ports:
      - 127.0.0.1:8082:80
    restart: always

  pma:
    container_name: pma
    env_file: .env
    image: phpmyadmin/phpmyadmin:5.0
    restart: always
    links:
      - mysql:mysql
    ports:
      - 127.0.0.1:8081:80
    environment:
      PMA_ABSOLUTE_URI: http://localhost:8081
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

networks:
  default:
    driver: bridge
